file(READ "${VT100_PROJECT_SOURCE_DIRECTORY}/src/tests/high-score-cases.json" CASES)
string(JSON CASE GET "${CASES}" "${MAME_TEST_CASE}")

# Non-game words are sentinels, with usable 80-column terminal settings.
set(DEFAULTS 0 8 110 32 208 80 0 32 0 224 224)
set(CHECKSUM 1)
foreach(INDEX RANGE 0 99)
    if(INDEX LESS 39)
        set(WORD 128)
    elseif(INDEX LESS 50)
        math(EXPR OFFSET "${INDEX} - 39")
        list(GET DEFAULTS ${OFFSET} WORD)
    elseif(INDEX EQUAL 50)
        set(WORD "${CHECKSUM}")
    else()
        math(EXPR WORD "(${INDEX} * 137 + 19) & 0x3fff")
    endif()
    if(INDEX LESS 50)
        math(EXPR CHECKSUM "(((${CHECKSUM} << 1) | (${CHECKSUM} >> 7)) & 255) ^ ${WORD}")
    endif()
    set(NVR_${INDEX} "${WORD}")
endforeach()

foreach(SLOT RANGE 0 9)
    string(JSON SCORE GET "${CASE}" scores ${SLOT})
    string(JSON INITIALS GET "${CASE}" initials ${SLOT})
    math(EXPR INDEX "51 + ${SLOT}")
    set(NVR_${INDEX} "${SCORE}")
    set(SCORE_${SLOT} "${SCORE}")
    set(INITIALS_${SLOT} "${INITIALS}")
endforeach()

function(pack_initials)
    set(CHARACTERS "")
    foreach(SLOT RANGE 0 9)
        string(APPEND CHARACTERS "${INITIALS_${SLOT}}")
    endforeach()
    foreach(PAIR RANGE 0 14)
        math(EXPR OFFSET "${PAIR} * 2")
        string(SUBSTRING "${CHARACTERS}" ${OFFSET} 2 CHARS)
        string(HEX "${CHARS}" HEX)
        string(SUBSTRING "${HEX}" 0 2 FIRST)
        string(SUBSTRING "${HEX}" 2 2 SECOND)
        math(EXPR WORD "(0x${FIRST} - 32) | ((0x${SECOND} - 32) << 6)")
        math(EXPR INDEX "61 + ${PAIR}")
        set(NVR_${INDEX} "${WORD}" PARENT_SCOPE)
    endforeach()
endfunction()

function(word_specs OUTPUT LITTLE_ENDIAN)
    set(SPECS)
    foreach(INDEX RANGE 0 99)
        math(EXPR WORD "${NVR_${INDEX}}" OUTPUT_FORMAT HEXADECIMAL)
        string(SUBSTRING "${WORD}" 2 -1 HEX)
        string(LENGTH "${HEX}" LENGTH)
        while(LENGTH LESS 4)
            string(PREPEND HEX "0")
            string(LENGTH "${HEX}" LENGTH)
        endwhile()
        if(LITTLE_ENDIAN)
            string(SUBSTRING "${HEX}" 0 2 HI)
            string(SUBSTRING "${HEX}" 2 2 LO)
            set(HEX "${LO}${HI}")
        endif()
        list(APPEND SPECS "${INDEX}=${HEX}")
    endforeach()
    list(JOIN SPECS "," SPECS)
    set(${OUTPUT} "${SPECS}" PARENT_SCOPE)
endfunction()

pack_initials()
word_specs(SEED FALSE)
foreach(SLOT RANGE 0 9)
    if(SCORE_${SLOT} GREATER 999 OR SCORE_${SLOT} EQUAL 0)
        set(SCORE_${SLOT} 0)
        set(INITIALS_${SLOT} "   ")
    endif()
endforeach()

string(JSON COUNT LENGTH "${CASE}" operations)
math(EXPR LAST "${COUNT} - 1")
foreach(OP RANGE 0 ${LAST})
    string(JSON SLOT GET "${CASE}" operations ${OP} slot)
    string(JSON CANCEL ERROR_VARIABLE ERROR GET "${CASE}" operations ${OP} cancel)
    if(SLOT LESS 0 OR CANCEL)
        continue()
    endif()
    foreach(DEST RANGE 9 1 -1)
        if(DEST GREATER SLOT)
            math(EXPR SOURCE "${DEST} - 1")
            set(SCORE_${DEST} "${SCORE_${SOURCE}}")
            set(INITIALS_${DEST} "${INITIALS_${SOURCE}}")
        endif()
    endforeach()
    string(JSON SCORE GET "${CASE}" operations ${OP} score)
    string(JSON AWARD ERROR_VARIABLE ERROR GET "${CASE}" operations ${OP} award)
    if(ERROR)
        set(AWARD 0)
    endif()
    math(EXPR SCORE_${SLOT} "(${SCORE} + ${AWARD}) % 1000")
    string(JSON INITIALS_${SLOT} GET "${CASE}" operations ${OP} initials)
endforeach()
foreach(SLOT RANGE 0 9)
    math(EXPR INDEX "51 + ${SLOT}")
    set(NVR_${INDEX} "${SCORE_${SLOT}}")
endforeach()
pack_initials()
word_specs(EXPECTED TRUE)

set(BASE_TEST_NAME "${MAME_TEST_NAME}")
function(run_phase PHASE)
    set(MAME_TEST_NAME "${BASE_TEST_NAME}-${PHASE}")
    set(MAME_TEST_PHASE "${PHASE}")
    set(MAME_EXPECT_NVR_WORDS "${EXPECTED}")
    if(PHASE STREQUAL "save")
        set(MAME_SEED_NVR_WORDS "${SEED}")
    else()
        set(MAME_INPUT_NVR_FILE "${VT100_BINARY_DIRECTORY}/mame-test/${BASE_TEST_NAME}-save/nvram/vt102/nvr")
        set(MAME_EXPECT_NVR_UNCHANGED TRUE)
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/run-mame-test.cmake")
endfunction()
run_phase(save)
run_phase(reload)
