if(NOT DEFINED VT100_BINARY_DIRECTORY)
    message(FATAL_ERROR "VT100_BINARY_DIRECTORY is required")
endif()

set(VT100_BASE_ROM "${VT100_BINARY_DIRECTORY}/vt100.bin")
set(VT100_BASE_SYMBOLS "${VT100_BINARY_DIRECTORY}/vt100.sym")
set(INVADERS_BASE_ROM "${VT100_BINARY_DIRECTORY}/invaders.bin")
set(INVADERS_AVO_ROM "${VT100_BINARY_DIRECTORY}/invaders-avo.bin")
set(INVADERS_BASE_SYMBOLS "${VT100_BINARY_DIRECTORY}/invaders.sym")
set(INVADERS_BASE_INCLUDE "${VT100_BINARY_DIRECTORY}/invaders-base.inc")
set(INVADERS_AVO_SYMBOLS "${VT100_BINARY_DIRECTORY}/invaders-avo.sym")

set(INVADERS_SPLIT_ROM_IMAGES
    invaders-1.bin
    invaders-2.bin
    invaders-3.bin
    invaders-4.bin
)

set(REQUIRED_INVADERS_FILES
    "${VT100_BASE_ROM}"
    "${VT100_BASE_SYMBOLS}"
    "${INVADERS_BASE_ROM}"
    "${INVADERS_AVO_ROM}"
    "${INVADERS_BASE_SYMBOLS}"
    "${INVADERS_BASE_INCLUDE}"
    "${INVADERS_AVO_SYMBOLS}"
)
foreach(INVADERS_SPLIT_ROM_IMAGE IN LISTS INVADERS_SPLIT_ROM_IMAGES)
    list(APPEND REQUIRED_INVADERS_FILES "${VT100_BINARY_DIRECTORY}/${INVADERS_SPLIT_ROM_IMAGE}")
endforeach()

foreach(REQUIRED_INVADERS_FILE IN LISTS REQUIRED_INVADERS_FILES)
    if(NOT EXISTS "${REQUIRED_INVADERS_FILE}")
        message("SKIP: Invaders ROM artifacts are not built; missing ${REQUIRED_INVADERS_FILE}")
        return()
    endif()
endforeach()

function(assert_file_size FILE_NAME EXPECTED_SIZE)
    file(SIZE "${FILE_NAME}" ACTUAL_SIZE)
    if(NOT ACTUAL_SIZE EQUAL EXPECTED_SIZE)
        message(FATAL_ERROR "Expected ${FILE_NAME} to be ${EXPECTED_SIZE} bytes; got ${ACTUAL_SIZE}")
    endif()
endfunction()

function(read_symbol SYMBOL_FILE SYMBOL_NAME OUTPUT_VARIABLE)
    file(STRINGS "${SYMBOL_FILE}" SYMBOL_FILE_LINES)
    set(SYMBOL_ADDRESSES "")
    foreach(SYMBOL_LINE IN LISTS SYMBOL_FILE_LINES)
        if(SYMBOL_LINE MATCHES "^([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])[ \t]+${SYMBOL_NAME}$")
            list(APPEND SYMBOL_ADDRESSES "${CMAKE_MATCH_1}")
        elseif(SYMBOL_LINE MATCHES "^${SYMBOL_NAME}[ \t]+[Ee][Qq][Uu][ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])[Hh]$")
            list(APPEND SYMBOL_ADDRESSES "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    list(LENGTH SYMBOL_ADDRESSES SYMBOL_ADDRESS_COUNT)
    if(NOT SYMBOL_ADDRESS_COUNT EQUAL 1)
        message(FATAL_ERROR "Expected exactly one ${SYMBOL_NAME} symbol in ${SYMBOL_FILE}; got ${SYMBOL_ADDRESS_COUNT}")
    endif()
    list(GET SYMBOL_ADDRESSES 0 SYMBOL_ADDRESS)
    string(TOUPPER "${SYMBOL_ADDRESS}" SYMBOL_ADDRESS)
    set(${OUTPUT_VARIABLE} "${SYMBOL_ADDRESS}" PARENT_SCOPE)
endfunction()

function(assert_symbol_in_window SYMBOL_NAME SYMBOL_ADDRESS)
    math(EXPR SYMBOL_VALUE "0x${SYMBOL_ADDRESS}")
    if(SYMBOL_VALUE LESS 32768 OR SYMBOL_VALUE GREATER 40959)
        message(FATAL_ERROR "${SYMBOL_NAME} is outside the AVO ROM window: 0x${SYMBOL_ADDRESS}")
    endif()
endfunction()

function(assert_symbol_equals SYMBOL_NAME SYMBOL_ADDRESS EXPECTED_ADDRESS)
    if(NOT SYMBOL_ADDRESS STREQUAL EXPECTED_ADDRESS)
        message(FATAL_ERROR "${SYMBOL_NAME} expected 0x${EXPECTED_ADDRESS}; got 0x${SYMBOL_ADDRESS}")
    endif()
endfunction()

function(hex_byte HEX_DATA BYTE_OFFSET OUTPUT_VARIABLE)
    math(EXPR HEX_OFFSET "${BYTE_OFFSET} * 2")
    string(SUBSTRING "${HEX_DATA}" ${HEX_OFFSET} 2 BYTE_VALUE)
    string(TOUPPER "${BYTE_VALUE}" BYTE_VALUE)
    set(${OUTPUT_VARIABLE} "${BYTE_VALUE}" PARENT_SCOPE)
endfunction()

function(assert_hex_byte HEX_DATA BYTE_OFFSET EXPECTED_BYTE DESCRIPTION)
    hex_byte("${HEX_DATA}" ${BYTE_OFFSET} ACTUAL_BYTE)
    if(NOT ACTUAL_BYTE STREQUAL EXPECTED_BYTE)
        message(FATAL_ERROR "${DESCRIPTION} expected byte ${EXPECTED_BYTE}; got ${ACTUAL_BYTE}")
    endif()
endfunction()

function(assert_jump_target HEX_DATA BYTE_OFFSET EXPECTED_TARGET DESCRIPTION)
    hex_byte("${HEX_DATA}" ${BYTE_OFFSET} OPCODE)
    math(EXPR TARGET_LOW_OFFSET "${BYTE_OFFSET} + 1")
    math(EXPR TARGET_HIGH_OFFSET "${BYTE_OFFSET} + 2")
    hex_byte("${HEX_DATA}" ${TARGET_LOW_OFFSET} TARGET_LOW)
    hex_byte("${HEX_DATA}" ${TARGET_HIGH_OFFSET} TARGET_HIGH)
    set(ACTUAL_TARGET "${TARGET_HIGH}${TARGET_LOW}")
    if(NOT OPCODE STREQUAL "C3")
        message(FATAL_ERROR "${DESCRIPTION} expected jmp opcode C3; got ${OPCODE}")
    endif()
    if(NOT ACTUAL_TARGET STREQUAL EXPECTED_TARGET)
        message(FATAL_ERROR "${DESCRIPTION} expected target 0x${EXPECTED_TARGET}; got 0x${ACTUAL_TARGET}")
    endif()
endfunction()

function(assert_call_target HEX_DATA BYTE_OFFSET EXPECTED_TARGET DESCRIPTION)
    hex_byte("${HEX_DATA}" ${BYTE_OFFSET} OPCODE)
    math(EXPR TARGET_LOW_OFFSET "${BYTE_OFFSET} + 1")
    math(EXPR TARGET_HIGH_OFFSET "${BYTE_OFFSET} + 2")
    hex_byte("${HEX_DATA}" ${TARGET_LOW_OFFSET} TARGET_LOW)
    hex_byte("${HEX_DATA}" ${TARGET_HIGH_OFFSET} TARGET_HIGH)
    set(ACTUAL_TARGET "${TARGET_HIGH}${TARGET_LOW}")
    if(NOT OPCODE STREQUAL "CD")
        message(FATAL_ERROR "${DESCRIPTION} expected call opcode CD; got ${OPCODE}")
    endif()
    if(NOT ACTUAL_TARGET STREQUAL EXPECTED_TARGET)
        message(FATAL_ERROR "${DESCRIPTION} expected target 0x${EXPECTED_TARGET}; got 0x${ACTUAL_TARGET}")
    endif()
endfunction()

function(append_allowed_range OUTPUT_VARIABLE FIRST_OFFSET BYTE_COUNT)
    set(ALLOWED_OFFSETS ${${OUTPUT_VARIABLE}})
    math(EXPR LAST_OFFSET "${FIRST_OFFSET} + ${BYTE_COUNT} - 1")
    foreach(ALLOWED_OFFSET RANGE ${FIRST_OFFSET} ${LAST_OFFSET})
        list(APPEND ALLOWED_OFFSETS "${ALLOWED_OFFSET}")
    endforeach()
    set(${OUTPUT_VARIABLE} "${ALLOWED_OFFSETS}" PARENT_SCOPE)
endfunction()

function(append_allowed_symbol OUTPUT_VARIABLE SYMBOL_ADDRESS)
    set(ALLOWED_OFFSETS ${${OUTPUT_VARIABLE}})
    math(EXPR SYMBOL_OFFSET "0x${SYMBOL_ADDRESS}")
    list(APPEND ALLOWED_OFFSETS "${SYMBOL_OFFSET}")
    set(${OUTPUT_VARIABLE} "${ALLOWED_OFFSETS}" PARENT_SCOPE)
endfunction()

assert_file_size("${INVADERS_BASE_ROM}" 8192)
assert_file_size("${INVADERS_AVO_ROM}" 8192)

set(INVADERS_SPLIT_OFFSET 0)
foreach(INVADERS_SPLIT_ROM_IMAGE IN LISTS INVADERS_SPLIT_ROM_IMAGES)
    set(INVADERS_SPLIT_ROM "${VT100_BINARY_DIRECTORY}/${INVADERS_SPLIT_ROM_IMAGE}")
    assert_file_size("${INVADERS_SPLIT_ROM}" 2048)

    file(READ "${INVADERS_BASE_ROM}" EXPECTED_SPLIT_HEX OFFSET ${INVADERS_SPLIT_OFFSET} LIMIT 2048 HEX)
    file(READ "${INVADERS_SPLIT_ROM}" ACTUAL_SPLIT_HEX HEX)
    if(NOT ACTUAL_SPLIT_HEX STREQUAL EXPECTED_SPLIT_HEX)
        message(FATAL_ERROR "${INVADERS_SPLIT_ROM_IMAGE} does not match invaders.bin at offset ${INVADERS_SPLIT_OFFSET}")
    endif()
    math(EXPR INVADERS_SPLIT_OFFSET "${INVADERS_SPLIT_OFFSET} + 2048")
endforeach()

read_symbol("${INVADERS_AVO_SYMBOLS}" inv_enter_impl INV_ENTER_IMPL)
read_symbol("${INVADERS_AVO_SYMBOLS}" inv_idle_impl INV_IDLE_IMPL)
read_symbol("${INVADERS_AVO_SYMBOLS}" inv_exit_impl INV_EXIT_IMPL)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_enter INV_ENTER)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_idle INV_IDLE)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_exit INV_EXIT)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_idle_hook INV_IDLE_HOOK)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_setup_keys_hook INV_SETUP_KEYS_HOOK)
read_symbol("${INVADERS_BASE_INCLUDE}" inv_active INV_ACTIVE)
read_symbol("${INVADERS_BASE_INCLUDE}" idle_loop INVADERS_IDLE_LOOP)
read_symbol("${INVADERS_BASE_INCLUDE}" keyboard_tick INVADERS_KEYBOARD_TICK)
read_symbol("${INVADERS_BASE_INCLUDE}" setup_keys INVADERS_SETUP_KEYS)
read_symbol("${INVADERS_BASE_INCLUDE}" rom1_checksum INVADERS_ROM1_CHECKSUM)
read_symbol("${INVADERS_BASE_INCLUDE}" rom2_checksum INVADERS_ROM2_CHECKSUM)
read_symbol("${INVADERS_BASE_INCLUDE}" rom3_checksum INVADERS_ROM3_CHECKSUM)
read_symbol("${INVADERS_BASE_INCLUDE}" rom4_checksum INVADERS_ROM4_CHECKSUM)
read_symbol("${VT100_BASE_SYMBOLS}" idle_loop VT100_IDLE_LOOP)
read_symbol("${VT100_BASE_SYMBOLS}" keyboard_tick VT100_KEYBOARD_TICK)
read_symbol("${VT100_BASE_SYMBOLS}" setup_keys VT100_SETUP_KEYS)
assert_symbol_in_window(inv_enter_impl "${INV_ENTER_IMPL}")
assert_symbol_in_window(inv_idle_impl "${INV_IDLE_IMPL}")
assert_symbol_in_window(inv_exit_impl "${INV_EXIT_IMPL}")
assert_symbol_in_window(inv_enter "${INV_ENTER}")
assert_symbol_in_window(inv_idle "${INV_IDLE}")
assert_symbol_in_window(inv_exit "${INV_EXIT}")
assert_symbol_in_window(inv_idle_hook "${INV_IDLE_HOOK}")
assert_symbol_in_window(inv_setup_keys_hook "${INV_SETUP_KEYS_HOOK}")
assert_symbol_equals(inv_active "${INV_ACTIVE}" "3FFF")
assert_symbol_equals(idle_loop "${INVADERS_IDLE_LOOP}" "${VT100_IDLE_LOOP}")
assert_symbol_equals(keyboard_tick "${INVADERS_KEYBOARD_TICK}" "${VT100_KEYBOARD_TICK}")
assert_symbol_equals(setup_keys "${INVADERS_SETUP_KEYS}" "${VT100_SETUP_KEYS}")

file(READ "${VT100_BASE_ROM}" VT100_BASE_HEX HEX)
file(READ "${INVADERS_BASE_ROM}" INVADERS_BASE_HEX HEX)
math(EXPR IDLE_LOOP_OFFSET "0x${INVADERS_IDLE_LOOP}")
math(EXPR SETUP_KEYS_HOOK_OFFSET "0x${INVADERS_SETUP_KEYS} + 6")
math(EXPR SETUP_KEYS_HOOK_CPI_OFFSET "${SETUP_KEYS_HOOK_OFFSET} + 1")
math(EXPR SETUP_KEYS_HOOK_S_OFFSET "${SETUP_KEYS_HOOK_OFFSET} + 2")

assert_call_target("${VT100_BASE_HEX}" ${IDLE_LOOP_OFFSET} "${VT100_KEYBOARD_TICK}" "idle_loop displaced call")
assert_call_target("${INVADERS_BASE_HEX}" ${IDLE_LOOP_OFFSET} "${INV_IDLE_HOOK}" "idle_loop Invaders hook")
assert_hex_byte("${VT100_BASE_HEX}" ${SETUP_KEYS_HOOK_OFFSET} "78" "setup_keys displaced mov a,b")
assert_hex_byte("${VT100_BASE_HEX}" ${SETUP_KEYS_HOOK_CPI_OFFSET} "FE" "setup_keys displaced cpi opcode")
assert_hex_byte("${VT100_BASE_HEX}" ${SETUP_KEYS_HOOK_S_OFFSET} "53" "setup_keys displaced 'S' operand")
assert_call_target("${INVADERS_BASE_HEX}" ${SETUP_KEYS_HOOK_OFFSET} "${INV_SETUP_KEYS_HOOK}" "setup_keys Invaders hook")

set(ALLOWED_DIFF_OFFSETS "")
append_allowed_range(ALLOWED_DIFF_OFFSETS ${IDLE_LOOP_OFFSET} 3)
append_allowed_range(ALLOWED_DIFF_OFFSETS ${SETUP_KEYS_HOOK_OFFSET} 3)
append_allowed_symbol(ALLOWED_DIFF_OFFSETS "${INVADERS_ROM1_CHECKSUM}")
append_allowed_symbol(ALLOWED_DIFF_OFFSETS "${INVADERS_ROM2_CHECKSUM}")
append_allowed_symbol(ALLOWED_DIFF_OFFSETS "${INVADERS_ROM3_CHECKSUM}")
append_allowed_symbol(ALLOWED_DIFF_OFFSETS "${INVADERS_ROM4_CHECKSUM}")

foreach(BASE_OFFSET RANGE 0 8191)
    hex_byte("${VT100_BASE_HEX}" ${BASE_OFFSET} VT100_BYTE)
    hex_byte("${INVADERS_BASE_HEX}" ${BASE_OFFSET} INVADERS_BYTE)
    if(NOT VT100_BYTE STREQUAL INVADERS_BYTE)
        list(FIND ALLOWED_DIFF_OFFSETS "${BASE_OFFSET}" ALLOWED_INDEX)
        if(ALLOWED_INDEX EQUAL -1)
            message(FATAL_ERROR "Unexpected Invaders base ROM byte difference at 0x${BASE_OFFSET}: vt100=${VT100_BYTE} invaders=${INVADERS_BYTE}")
        endif()
    endif()
endforeach()

file(READ "${INVADERS_AVO_ROM}" INVADERS_AVO_HEADER HEX OFFSET 0 LIMIT 12)
string(TOUPPER "${INVADERS_AVO_HEADER}" INVADERS_AVO_HEADER)
assert_hex_byte("${INVADERS_AVO_HEADER}" 0 "C3" "inv_enter")
assert_hex_byte("${INVADERS_AVO_HEADER}" 3 "C3" "inv_idle")
assert_hex_byte("${INVADERS_AVO_HEADER}" 6 "C3" "inv_exit")
assert_hex_byte("${INVADERS_AVO_HEADER}" 9 "C3" "inv_idle_hook")
assert_jump_target("${INVADERS_AVO_HEADER}" 0 "${INV_ENTER_IMPL}" "inv_enter")
assert_jump_target("${INVADERS_AVO_HEADER}" 3 "${INV_IDLE_IMPL}" "inv_idle")
assert_jump_target("${INVADERS_AVO_HEADER}" 6 "${INV_EXIT_IMPL}" "inv_exit")
read_symbol("${INVADERS_AVO_SYMBOLS}" inv_idle_hook_impl INV_IDLE_HOOK_IMPL)
read_symbol("${INVADERS_AVO_SYMBOLS}" inv_setup_keys_hook_impl INV_SETUP_KEYS_HOOK_IMPL)
assert_symbol_in_window(inv_idle_hook_impl "${INV_IDLE_HOOK_IMPL}")
assert_symbol_in_window(inv_setup_keys_hook_impl "${INV_SETUP_KEYS_HOOK_IMPL}")
assert_jump_target("${INVADERS_AVO_HEADER}" 9 "${INV_IDLE_HOOK_IMPL}" "inv_idle_hook")

file(READ "${INVADERS_AVO_ROM}" INVADERS_AVO_SETUP_HOOK HEX OFFSET 12 LIMIT 3)
string(TOUPPER "${INVADERS_AVO_SETUP_HOOK}" INVADERS_AVO_SETUP_HOOK)
assert_jump_target("${INVADERS_AVO_SETUP_HOOK}" 0 "${INV_SETUP_KEYS_HOOK_IMPL}" "inv_setup_keys_hook")

message(STATUS "Invaders ROM layout verified")
