if(NOT DEFINED LST_FILE)
    message(FATAL_ERROR "LST_FILE is required")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

file(STRINGS "${LST_FILE}" LST_LINES REGEX "([Ll][Aa][Bb][Ee][Ll]|EQU)")

set(OUTPUT_TEXT "; Generated from ${LST_FILE}. Do not edit.\n")
foreach(LINE IN LISTS LST_LINES)
    string(STRIP "${LINE}" LINE)
    string(TOUPPER "${LINE}" UPPER_LINE)
    string(FIND "${UPPER_LINE}" "LABEL" LABEL_POS)
    string(FIND "${UPPER_LINE}" "EQU" EQU_POS)
    string(REGEX MATCH "^[A-Za-z0-9_]+" NAME "${LINE}")
    string(REGEX MATCH "[A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9]h$" ADDRESS_H "${LINE}")
    if(NAME AND ADDRESS_H AND (NOT LABEL_POS EQUAL -1 OR NOT EQU_POS EQUAL -1))
        if(ADDRESS_H MATCHES "^[A-Fa-f]")
            set(ADDRESS_H "0${ADDRESS_H}")
        endif()
        string(APPEND OUTPUT_TEXT "${NAME}\tequ\t${ADDRESS_H}\n")
    endif()
endforeach()

file(WRITE "${OUTPUT_FILE}" "${OUTPUT_TEXT}")
