name: CMake

on:
  push:
  pull_request:

jobs:
  cmake:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Linux build prerequisites
        if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo dpkg-reconfigure man-db
          sudo apt-get update
          sudo apt-get install --yes autoconf autoconf-archive automake libtool libltdl-dev

      - name: Bootstrap vcpkg
        if: runner.os == 'Linux'
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Bootstrap vcpkg
        if: runner.os == 'Windows'
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure, build, and test
        run: cmake --workflow --preset default
